/**
 * UI Event Types from host application
 * These events are dispatched to trigger actions in the host app
 */

export enum UI_EVENT_TYPE {
  // Geoprocessing Events
  GEOPROCESSING_SERVERS = 2011,
  GEOPROCESSING_ADD_JOB = 2012,
  GEOPROCESSING_LIST_JOBS = 2013,

  // Application Events
  APPLICATION_LOGFILE = 10001,
  APPLICATION_ABOUT = 10000,
  APPLICATION_OPEN_EXTERNAL_LINK = 10002,

  // Session Events
  SESSION_NEW_WORKSPACE = 511,
  SESSION_EXPORT_WORKSPACE = 512,
  SESSION_IMPORT_WORKSPACE = 513,
  SESSION_EXPLORE_WORKSPACES = 514,
  SESSION_SAVE_AS_WORKSPACE = 515,
  SESSION_SAVE_WORKSPACE = 516,
  SESSION_LOGIN_AGAIN = 517,
  SESSION_LIST_WFST_LOCKS = 518,
  SESSION_ADMIN_DASHBOARD = 500,
  SESSION_PREFERENCES = 501,
  SESSION_CATALOG_REGISTER = 504,
  SESSION_CATALOG_FILTER = 505,
  SESSION_LOGOUT = 506,
  SESSION_REFRESH = 2021,

  // Tools Events
  TOOLS_ADVANCED_SEARCH = 301,
  TOOLS_SCREENSHOT = 302,
  TOOLS_EDIT_MEASURE = 303,
  TOOLS_BROWSE_CATALOGS = 304,
  TOOLS_ECDIS_SETTINGS = 305,
  TOOLS_SLICING = 306,

  // View Events
  VIEW_FULL_SCREEN = 201,
  VIEW_MOUSE_COORDINATES = 202,
  VIEW_SCALE_INDICATOR = 203,
  VIEW_MAP_PROJECTION = 204,
  VIEW_COMPASS_CONTROL = 205,
  VIEW_PAN_CONTROL = 206,
  VIEW_ZOOM_CONTROL = 207,
  VIEW_OVERVIEW_WINDOW = 209,
  VIEW_LAYER_MANAGER = 210,
  VIEW_TABLE_VIEW = 212,
  VIEW_CROSSSECTION_WINDOW = 214,
  VIEW_CLOSE_CUSTOM_WINDOW = 215,
  VIEW_CLOSE_ATTEMPT_CUSTOM_WINDOW = 216,

  // Other Events
  NO_EVENT = 0,
  SHOPPING_CART = 2003,
  SHOW_EFFECTS_TOOLS = 2004,
  SHOW_PICTURE_SETTINGS = 2005,
  CATALOG_ADVANCED_SEARCH = 2020,
}

export interface UIEventInterface {
  action: UI_EVENT_TYPE;
  parameters?: any;
}
